version: "3.2"

services:
  elk:
    image: sebp/elk:643
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - type: bind
        source: ./config/logstash/
        target: /etc/logstash/conf.d/